/**
 * Iconik Posters — icon system.
 *
 * Single source of truth for every icon in the app. The whole UI draws from
 * `react-icons`: Tabler (`tb`) for the interface set — it matches the stroke
 * weight and 24px grid the design was built on — and Font Awesome 6 (`fa6`)
 * for the social brand marks, which the stroke sets don't carry.
 *
 * Import icons from here, never from `react-icons/*` directly, so the mapping
 * stays swappable in one place:
 *
 *   import { ShoppingBag, Heart } from "@/components/icons";
 */
export type { IconType } from "react-icons";

export {
  TbAdjustmentsHorizontal as SlidersHorizontal,
  TbAlertTriangle as AlertTriangle,
  TbArrowLeft as ArrowLeft,
  TbArrowRight as ArrowRight,
  TbArrowsMaximize as Expand,
  TbAt as AtSign,
  TbBed as Bed,
  TbBell as Bell,
  TbBook as BookOpen,
  TbBuilding as Building2,
  TbBuildingStore as Store,
  TbCar as Car,
  TbCash as Banknote,
  TbCheck as Check,
  TbChevronDown as ChevronDown,
  TbChevronLeft as ChevronLeft,
  TbChevronRight as ChevronRight,
  TbChevronUp as ChevronUp,
  TbCircle as Circle,
  TbCircleCheck as CheckCircle2,
  TbCircleX as XCircle,
  TbClock as Clock,
  TbCloudUpload as UploadCloud,
  TbCoffee as Coffee,
  TbCreditCard as CreditCard,
  TbCurrencyRupee as IndianRupee,
  TbDeviceFloppy as Save,
  TbDeviceGamepad2 as Gamepad2,
  TbDeviceLaptop as Laptop,
  TbDots as MoreHorizontal,
  TbDownload as Download,
  TbExternalLink as ExternalLink,
  TbEye as Eye,
  TbEyeOff as EyeOff,
  TbFileText as FileText,
  TbFlame as Flame,
  TbFolders as FolderTree,
  TbGift as Gift,
  TbGripVertical as GripVertical,
  TbHeart as Heart,
  TbHome as Home,
  TbLayoutDashboard as LayoutDashboard,
  TbLink as Link2,
  TbLoader2 as Loader2,
  TbLock as Lock,
  TbLogout as LogOut,
  TbMail as Mail,
  TbMapPin as MapPin,
  TbMenu2 as Menu,
  TbMessageQuestion as MessageCircleQuestion,
  TbMicrophone as Mic,
  TbMinus as Minus,
  TbMoodSad as Frown,
  TbMoon as Moon,
  TbMovie as Clapperboard,
  TbMusic as Music4,
  TbPackage as Package,
  TbPackageExport as PackageCheck,
  TbPackages as PackageSearch,
  TbPalette as Palette,
  TbPencil as Pencil,
  TbPhoto as ImageIcon,
  TbPlus as Plus,
  TbQuote as Quote,
  TbRocket as Rocket,
  TbRosetteDiscountCheck as BadgeCheck,
  TbRotate as RotateCcw,
  TbSearch as Search,
  TbSend as Send,
  TbSettings as Settings,
  TbShape as Shapes,
  TbShare as Share2,
  TbShieldCheck as ShieldCheck,
  TbShoppingBag as ShoppingBag,
  TbShoppingCart as ShoppingCart,
  TbSofa as Sofa,
  TbSparkles as Sparkles,
  TbStar as Star,
  TbStars as Sparkle,
  TbSun as Sun,
  TbTag as Tag,
  TbThumbUp as ThumbsUp,
  TbTicket as Ticket,
  TbTrash as Trash2,
  TbTrendingUp as TrendingUp,
  TbTrophy as Trophy,
  TbTruck as Truck,
  TbUser as User,
  TbUsers as Users,
  TbX as X,
} from "react-icons/tb";

/** Social brand marks — only Font Awesome carries these. */
export {
  FaInstagram as Instagram,
  FaFacebookF as Facebook,
  FaYoutube as Youtube,
} from "react-icons/fa6";
